### PR TITLE
set() on Row/Record/Related

### PR DESCRIPTION
**Pull request by yespire**

### CODE REVIEW

**Comment by pmjones** [comment]
Is this essentially the same thing as #12 and #16?

**Comment by pmjones** [comment]
OK, some notes:
1. I don't think we need the Atlas::patch() method; you're going to have the Record in hand already, so no need to pass it through Atlas.
2. Likewise, I don't think we need the AbstractMapper::patch() method either, for the same reason.
3. To streamlime/simplify Row::set(), accept only an array of $colsVals. If someone want to set a single value, they can pass a single-value array (e.g., `$row->set(['colname' => 'value'])`).
4. Record::set() doesn't look right. Start by making it match the `Row::set()` signature, then ignore relateds for the moment and pass the values directly through to the row.

Finally, please use PSR-2 style; braces for conditional structures go on the same line, not the next line.

Ping me when you have made those changes and I will review again.

Thanks!

**Comment by yespire** [comment]
updated, set() is kept, patch() removed

**Comment by yespire** [comment]
I noticed that a couple of IDE files are committed by accident, should I close and create a new PR ?

**Comment by harikt** [comment]
@yespire you can remove those files and commit . And do a rebase for this is not yet merged. So no need to close and start. 

PS : https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by pmjones** [comment]
Yes, this is better. Thanks!

**Pull request merged**
