### PR TITLE
Read and write from different connection in the ConnectionLocator

### PR DESCRIPTION
**Pull request by harikt**
Hi Paul,

So there is a question whether we need to support passing the name to the `getReadConnection()` and `getWriteConnection` in `AbstractMapper` and there by to the `AbstractTable` class.

Also I am not sure the best way to write a unit test for this. But I would like to discuss this making a small PR with my limited capabilities.

Thank you.

### CODE REVIEW

**Comment by pmjones** [comment]
/me nods

It's a valid need. However, the Table class will be overwritten when the skeleton gets regenerated, so those values on the Table properties will be lost.

**Comment by harikt** [comment]
> However, the Table class will be overwritten when the skeleton gets regenerated, so those values on the Table properties will be lost.

@pmjones that is valid. I haven't thought about the re-generation. But as far as people use a version control and is doing careful review the problem with that can be overridden. 

Another thing I feel is probably passing the connection names to `getReadConnection` and `getWriteConnection` will also be helpful if users need to get different connection ?

**Comment by pmjones** [comment]
I wonder if the thing to do is pass $readConnection and $writeConnection to the Table constructor, rather than a ConnectionLocator. The connections themselves should be lazy ExtendedPdo anyway, so creating them should not create a database hit. The AtlasContainer might then let you specify which connections to use for which tables.

**Comment by harikt** [comment]
How about introducing a connection trait ? 

``` php
<?php
trait Connection
{
     /**
     *
     * The name of the read connection in registry entry.
     *
     * @var string
     *
     */
    protected $readConnectionName = NULL;

    /**
     *
     * The name of the write connection in registry entry.
     *
     * @var string
     *
     */
    protected $writeConnectionName = NULL;
}
```

That actually solves the problem even if they are generated I believe. I don't like the suggested way you mentioned.

**Comment by harikt** [comment]
I have been thinking and my last comment about Connection trait seems dump :P .

**Comment by pmjones** [comment]
Heh -- it's kind of a tough problem at at the Table level.

**Comment by harikt** [comment]
There is another possible solution. Not sure if you like or not ;) .

Current structure is as 

```
Author
├── AuthorMapper.php
├── AuthorRecord.php
├── AuthorRecordSet.php
└── AuthorTable.php
```

This will change to something as below. And now you have a generated base table class which can be always modified when there is a change in table.

```
Author
├── AuthorMapper.php
├── AuthorRecord.php
├── AuthorRecordSet.php
├── AuthorTable.php ( no methods or functions . If the user needs they can define the read / write connection name )
└── Generated
    └── BaseAuthorTable.php ( old AuthorTable )
```

And `AuthorTable extends Generated\BaseAuthorTable` . The `AuthorTable` can have the read connection name.

The problem with moving to container as mentioned in comment  (https://github.com/atlasphp/Atlas.Orm/pull/33#issuecomment-254632930) is it it makes api more cubersome. 

1. Do we need to pass the connection information in Mapper ? 
Seems no . Mapper is not responsible for the connection with table.

2. Then how do we pass the table information. ... 

ie why I have been thinking about other ways.

This may not a BC break, for the classes already exists in the system. But there is some problems related with this, which need to be addressed.

1. What happens when there is a change in table structure.
   a. The author tries to run the command to update table.
   b. It generates the table in Generated folder.
   c. There is already a Table class which is not updated nor extended.

We may want to see if there is a possible way to let composer tell or update these only for a certain version.

~~~Eg : post-install command, check old version , installed version. If it is less than x, do the changes. overwrite the table class extending base class. If not do nothing.~~~ only works for root composer.json .

UPDATE : May be add a bin/update-1.4 sort of script. So the users can run it manually.

This can check if the class extends the `Base*Table` class or not. If no overwrite with new one.

**Comment by pmjones** [comment]
@harikt I am closing this PR because I discovered other problems elsewhere (notably that Mapper::persist() would not honor transactions across multiple connections) that require a more extensive change related to this. So I am turning this PR down, *but* the related functionality has been incorporated as part of Atlas\Orm\Table\ConnectionManager in the 2.x branch.

Thanks for suggesting the feature and for your work on this PR.

**Comment by harikt** [comment]
sure. No problem. Thank you for adding it in 2.x .

**Pull request closed without merging**
