### PR TITLE
add case-insensitivity option. fixes #38 for @harikt

### PR DESCRIPTION
**Pull request by pmjones**

### CODE REVIEW

**Comment by harikt** [comment]
This works for me.

I hope we can assume the primary keys will never be uni-code characters ;) .

**Comment by pmjones** [comment]
> I hope we can assume the primary keys will never be uni-code characters ;) .

There's always one more problem isn't there? ;-)

**Comment by harikt** [comment]
There is no test for this, can you add one from https://github.com/atlasphp/Atlas.Orm/pull/38 .

**Comment by pmjones** [comment]
Wanted a somewhat lighter test, which is accomplished with 890fecf663fa2289411e2b2303aa2a82b3122cc4

**Pull request merged**
