### PR TITLE
Rename Table methods in todo

### PR DESCRIPTION
**Pull request by harikt**
Hi Paul, 

I was trying to pick up some of the todo stuffs.

Not sure if this is really you are looking for : 

Rename Table::insert(), update(), delete() to insertRow(), updateRow(), deleteRow(), and rename newInsert() to insert() , newUpdate() to update(), newDelete() to delete()

I wonder whether the insert() , update(), delete() etc need to be made public. But I am still not sure how they are executed if the Query objects are exposed.

Probably this may not be the PR you are looking for :-) .

### CODE REVIEW

**Comment by harikt** [comment]
May be you are looking to add class similar to MapperSelect ? So the queries are exposed and can be executed ?

**Comment by pmjones** [comment]
@harikt This is a good start, thanks. Yes, the idea will be make insert() et al public so that you can "reach down" into the lower levels to do lower-level stuff.

**Comment by pmjones** [comment]
Thanks for jump-starting this @harikt -- I have built on your work and pushed the result to 1.x.

**Comment by harikt** [comment]
Good to know Paul.

I would have worked some more, but was not sure where I was heading to :) .

Have a nice day ahead. 

Enjoy! .

**Pull request merged**
