### PR TITLE
atlas->patch(record, colsVals)

### PR DESCRIPTION
**Pull request by yespire**
support following use case after form submit:

$atlas->patch($article, $post); // if you have a lot of columns, save typing
$atlas->update($article);

### CODE REVIEW

**Comment by pmjones** [comment]
This might go better on the Row class. The logic can check array_key_exists($this->cols) in that case. Maybe call it `set()` rather than `patch()`?

Probably want a corresponding method on the Record class, that proxies to the Row method.

Should that corresponding Record method deal with the relateds at all, or only the Row cols?

**Comment by yespire** [comment]
PatchRecord idea is learnt from CakeOrm's [Table::patchEntity()](http://book.cakephp.org/3.0/en/orm/saving-data.html#validation-and-patchentity)

There are 2 separate things
1. need for mass assignments --- I agree that Row::set($colsVals) would be useful, in turn the classes sits on top of Row would use Row::set()
2. patchRecord() is meant for introducing another 2 events, beforePatch, afterPatch, which can be complementary to events -- beforeUpdate, afterUpdate

my counter argument for adding patchRecord():
1. atlas seems aiming for minimalistic, maybe patchRecord() should be application level code
2. most apps are not complex enough, too many options leads to confusion and misuse

**Comment by pmjones** [comment]
Patching a _record_ might be app-level code, but might work at the record level as well. Either way, it needs to be implemented at the row level first. If you can update this PR to use the method name `set()` instead of `patch()`, and to work at the row level, I can re-review.

(Thanks for taking the time to do this kind of work.)

**Comment by yespire** [comment]
Sure, I will send a PR later, closing this for now

**Comment by harikt** [comment]
@yespire you could probably make the change and commit so it will be reflected in this PR itself. Don't need to close.

**Pull request closed without merging**
