### PR TITLE
add more IDE cases to gitignore

### PR DESCRIPTION
**Pull request by yespire**

### CODE REVIEW

**Comment by pmjones** [comment]
Thanks for these. I should try to make them standard across all my packages.

**Comment by jakejohns** [comment]
@pmjones if you wish to include robust gitignore for all the packages, I might suggest the boilerplates:
https://github.com/github/gitignore

They're a little more robust than what's here, for example, vim, my editor of choice:
https://github.com/github/gitignore/blob/master/Global/Vim.gitignore

There's also a nice little utility I tend to use to ease the burden of this:
https://github.com/simonwhitaker/gibo

**Comment by opengeek** [comment]
Just throwing this out there...

I've read recently that the prevailing trend was not to have exclusions per project, but rather for users to exclude their IDE and other development platform dependent exclusions in their global gitignore instead? Perhaps this is not widely accepted yet? The idea of keeping the project clean and putting the burden on the developer-specific environment is certainly logical, but I'd like to hear more opinions.

**Comment by pmjones** [comment]
@opengeek Good grief, I didn't even know there _was_ a global .gitignore.

**Comment by jakejohns** [comment]
honestly, what @opengeek sez seems right to me.

**Comment by yespire** [comment]
Thank you for the information, I was not aware of the global gitignore for IDE cases either, hence the pull request. I do agree with the approach of using global gitignore to manage multiple projects.

However, I think for an open source package, we may save some hassle by having common IDE files covered, the rationale:
1. that some developers might not have proper global gitignore configured, hence the chance of introducing a file like .DS_Store, .idea in their commits
2. some extra .gitignore won't hurt even if there is overlapping global gitignore

**Comment by pmjones** [comment]
> that some developers might not have proper global gitignore configured

I think in that case, it has become our burden to educate them.

> some extra .gitignore won't hurt even if there is overlapping global gitignore

True, though not-having the overlap wouldn't hurt either.

I think the right thing to do here is encourage a global .gitignore for each developer, and limit package-specific ignores to package-specific concerns.

**Pull request merged**
