### PR TITLE
Possible [bug] When strings are primary key

### PR DESCRIPTION
**Pull request by harikt**
The data I have is imported from some where. I noticed in the data one record key value is small letter. This bug also depends on the database and collation. Eg : Sqlite seems failing, mysql can fetch the record regardless of the key value . ( `v5889` or `V5889` )

Problem is values are fetched. It sometimes misses the RecordSet.

You can test the normal pdo trying to get the records.

``` sql
-- Adminer 4.2.4 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `test1`;
CREATE TABLE `test1` (
  `id` char(10) NOT NULL,
  `name` varchar(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `test1` (`id`, `name`) VALUES
('B23', 'B23'),
('v5889',   'Hello');

DROP TABLE IF EXISTS `test2`;
CREATE TABLE `test2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `test1_id` char(10) NOT NULL,
  `name` varchar(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `test2` (`id`, `test1_id`, `name`) VALUES
(1, 'V5889',    'World'),
(2, 'B23',  'B23 World');
```

``` php
<?php
require __DIR__ . '/vendor/autoload.php';

$conn = require __DIR__ . '/conn.php';

$atlasContainer = new \Atlas\Orm\AtlasContainer($conn[0], $conn[1], $conn[2]);

$atlasContainer->setMappers([
    \Atlas\Orm\DataSource\Test1\Test1Mapper::CLASS,
    \Atlas\Orm\DataSource\Test2\Test2Mapper::CLASS,
]);

$atlas = $atlasContainer->getAtlas();

$record = $atlas->fetchRecord(
    \Atlas\Orm\DataSource\Test1\Test1Mapper::CLASS,
    'v5889', // if you don't ask to fetch records via `with` it fetches the value. 
    ['test2'] // you can remove comment and add comment and change to `v5889` to see various behaviours
);
echo " Record : " . $record->id . "\n";
echo " World : \n";

foreach($record->test2 as $r) {
    echo "Id : {$r->test1_id} {$r->name} \n";
}

$record = $atlas->fetchRecord(
    \Atlas\Orm\DataSource\Test1\Test1Mapper::CLASS,
    'B23',
    ['test2']
);
echo " Record : " . $record->id . "\n";
echo " World : \n";

foreach($record->test2 as $r) {
    echo "Id : {$r->test1_id} {$r->name} \n";
}

$locator = $atlasContainer->getConnectionLocator();
$connection = $locator->getDefault();
$records = $connection->fetchAll("SELECT * FROM test1 WHERE id = :id", ['id' => 'V5889']);
var_dump($records);
```

Running the above was resulting with 

``` php
Record : v5889
 World : 
 Record : B23
 World : 
Id : B23 B23 World 
/var/www/projects/github.com/harikt/Atlas.Orm/hello.php:42:
array(1) {
  [0] =>
  array(2) {
    'id' =>
    string(5) "v5889"
    'name' =>
    string(5) "Hello"
  }
}
```

If we use  

``` php
$record = $atlas->fetchRecord(
    \Atlas\Orm\DataSource\Test1\Test1Mapper::CLASS,
    'v5889'
);
```

It can fetch the record without any issues whether it is `V5889` or `v5889` doesn't matter. I have been looking into this but unable to figure out where it is causing the trouble.

### CODE REVIEW

**Comment by pmjones** [comment]
Is this something that happens with a plain PDO connection too?

**Comment by harikt** [comment]
> Is this something that happens with a plain PDO connection too?

No plain pdo is able to fetch the record. You can see in this example itself me getting the default connection and dumping the result.

**Comment by harikt** [comment]
@pmjones another example . Please see the values `V5889` and `v5889` . It can fetch things. But it has different behaviours depending on the order and case sensitive keys are passed.

``` php
<?php
require __DIR__ . '/vendor/autoload.php';

$conn = require __DIR__ . '/conn.php';

$atlasContainer = new \Atlas\Orm\AtlasContainer($conn[0], $conn[1], $conn[2]);

$atlasContainer->setMappers([
    \Atlas\Orm\DataSource\Test1\Test1Mapper::CLASS,
    \Atlas\Orm\DataSource\Test2\Test2Mapper::CLASS,
]);

$atlas = $atlasContainer->getAtlas();

$record = $atlas->fetchRecord(
    \Atlas\Orm\DataSource\Test1\Test1Mapper::CLASS,
    'V5889'
);
echo " Record : " . $record->id . "\n";

$record = $atlas->fetchRecord(
    \Atlas\Orm\DataSource\Test1\Test1Mapper::CLASS,
    'v5889',
    ['test2']
);
echo " Record : " . $record->id . "\n";
echo " World : \n";

foreach($record->test2 as $r) {
    echo "Id : {$r->test1_id} {$r->name} \n";
}
```

Output : 

```
Record : v5889
Record : v5889
World : 
```

**Comment by harikt** [comment]
@pmjones so I invested sometime looking into where the problem is . It is over https://github.com/atlasphp/Atlas.Orm/blob/6c5cb235aa48040182ea6b8f31974e6cc6fddf5e/src/Relationship/AbstractRelationship.php#L425 . Not sure actually why you are making sure the value is same ?

**Comment by pmjones** [comment]
Aha -- that's to check if two records are related. If all the native columns equal all the related foreign columns, it's a match.

**Comment by pmjones** [comment]
From what I can understand, the problem you're describing is that:
1. Fetching a record with a string primary key is _not_ case-sensitive (fetching by "id=Foo" will get you back a record where "id=foo").
2. But stitching together related records _is_ case-sensitive, so native=foo does not match foreign=Foo.

Do have that right?

**Comment by harikt** [comment]
@pmjones you are right with your findings. Only thing I noticed or probably doubt that sqlite is not working the way for foo and Foo.

**Comment by pmjones** [comment]
@harikt Any further thoughts on this?

**Comment by pmjones** [comment]
I have merged this PR into a local branch, and the tests fail, but it looks like they *should* fail.

The fixture inserts lowercase `v5889` into `test1`, and this line:

```
        $records = $this->connection->fetchAll("SELECT * FROM test1 WHERE id = :id", ['id' => 'V5889']);
```

... fails to find it, because it looks for upper-case `V5889`. (Changing the value to the lower-case makes it find the record.)

Likewise on the `test1` fixture, this code ...

```
        $actual = $this->atlas->fetchRecord(
            Test1Mapper::CLASS,
            'V5889',
            [
                'test2',
            ]
        );

        $this->assertSame('v5889', $actual->id);
```

... fails, because $actual is false, because the record is not found. But since there is no upper-case `V5889` value, is *should* fail to be found. Changing the search value to lower-case `v5889` causes it to pass.

So I don't think there's a problem in the code; as you say, it might be your SQLite installation somehow.

Please let me know if this continues to be a problem, and we'll see if we can track down the specific issue.

**Comment by harikt** [comment]
@pmjones did you tried with `PDO` and see if that was fetching regardless of the case?

This was actually a problem at the time, so was forced to choose some other path.

**Comment by pmjones** [comment]
I did not try with PDO, but I did try with SQLite at the command line, and it fetched only case-sensitively. That is, `SELECT * WHERE col = 'foo'` would return rows only where `col` was lower-case foo, not upper-case Foo. If you can paste a PDO-specific script that replicates the issue I'll try it locally.

**Comment by harikt** [comment]
@pmjones I am sorry that I wanted to repeat the same comments I wrote on https://github.com/atlasphp/Atlas.Orm/pull/38#issue-183744847

> I did not try with PDO, but I did try with SQLite at the command line, and it fetched only case-sensitively. 

This bug also depends on the database and collation. Eg : Sqlite seems failing, mysql can fetch the record regardless of the key value . ( v5889 or V5889 )

> That is, SELECT * WHERE col = 'foo' would return rows only where col was lower-case foo, not upper-case Foo. 

True, see my comment : https://github.com/atlasphp/Atlas.Orm/pull/38#issue-183744847 

> If you can paste a PDO-specific script that replicates the issue I'll try it locally.

Copying and pasting the same code from my earlier comments.

```
$locator = $atlasContainer->getConnectionLocator();
$connection = $locator->getDefault();
$records = $connection->fetchAll("SELECT * FROM test1 WHERE id = :id", ['id' => 'V5889']);
var_dump($records);
```

Please see the connection is actually a PDO instance . ( ExtendedPdo ) .

I know the code I am going to paste is still repeating, 

```sql
-- Adminer 4.2.5 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `test1`;
CREATE TABLE `test1` (
  `id` char(10) NOT NULL,
  `name` varchar(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `test1` (`id`, `name`) VALUES
('v5889',	'Hello');
```

```json
{
    "minimum-stability":"dev",
    "require": {
        "atlas/orm": "^1.0@alpha",
        "atlas/cli": "^0.4.0@alpha"
    },
    "autoload": {
        "psr-4": {
            "App\\DataSource\\": "src/App/DataSource/"
        }
    }
}
```

```php
// conn.php
<?php
// /path/to/conn.php
return ['mysql:dbname=test;host=localhost', 'username', 'password'];
```

```bash
./vendor/bin/atlas-skeleton.php --dir=./src/App/DataSource --conn=conn.php --table=test1 App\\DataSource\\Test1
```

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$conn = require __DIR__ . '/conn.php';

$atlasContainer = new \Atlas\Orm\AtlasContainer($conn[0], $conn[1], $conn[2]);

$atlasContainer->setMappers([
    \App\DataSource\Test1\Test1Mapper::CLASS,
]);

$atlas = $atlasContainer->getAtlas();

echo "Fetching v5889 \n";

$record = $atlas->fetchRecord(
    \App\DataSource\Test1\Test1Mapper::CLASS,
    'v5889',
    []
);
echo " ID : " . $record->id . "\n";
echo " Name : $record->name \n";

echo "Fetching V5889 \n";

$record = $atlas->fetchRecord(
    \App\DataSource\Test1\Test1Mapper::CLASS,
    'V5889',
    []
);

echo " ID : " . $record->id . "\n";
echo " Name : $record->name \n";

$locator = $atlasContainer->getConnectionLocator();
$connection = $locator->getDefault();

echo "Fetching V5889 via PDO \n";

$records = $connection->fetchAll("SELECT * FROM test1 WHERE id = :id", ['id' => 'V5889']);
var_dump($records);

echo "Fetching v5889 via PDO \n";

$records = $connection->fetchAll("SELECT * FROM test1 WHERE id = :id", ['id' => 'v5889']);
var_dump($records);
```

Please note, there is only one record with id : `v5889` .

I am testing with mysql.

The results it produce is 

```bash
php index.php
Fetching v5889 
 ID : v5889
 Name : Hello 
Fetching V5889 
 ID : v5889
 Name : Hello 
Fetching V5889 via PDO 
array(1) {
  [0]=>
  array(2) {
    ["id"]=>
    string(5) "v5889"
    ["name"]=>
    string(5) "Hello"
  }
}
Fetching v5889 via PDO 
array(1) {
  [0]=>
  array(2) {
    ["id"]=>
    string(5) "v5889"
    ["name"]=>
    string(5) "Hello"
  }
}
```

If you say that the value is case sensitive then it should not fetch the record itself.

Thank you.

**Comment by harikt** [comment]
@pmjones if you could, please fix this bug in 2.x . This is a real bug that I could not make use of Atlas.

**Comment by pmjones** [comment]
It occurred to me this morning that it might be as easy as a new method on the Relationships class; e.g., `$this->oneToOne('field', MapperClass::CLASS)->matchCase(false)`. Then the matching logic can apply strtolower() on each value. Make sense?

**Comment by harikt** [comment]
yes, that would be very nice to have.

**Comment by pmjones** [comment]
@harikt Please try the new `case-match` branch, which is the basis for PR #48, and let me know if that solves this problem.

**Comment by harikt** [comment]
@pmjones this actually is a failing test. So you can merge this I believe :) .

**Pull request closed without merging**
